use Biblioteca;

ALTER TABLE Solicitud
  ADD KEY idPersona(idPersona),
  ADD CONSTRAINT S_1 FOREIGN KEY (idPersona) REFERENCES Persona (id) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE DetalleSolicitud
  ADD KEY idSolicitud(idSolicitud),
  ADD KEY idRecurso(idRecurso),
  ADD CONSTRAINT DS_1 FOREIGN KEY (idSolicitud) REFERENCES Solicitud (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT DS_2 FOREIGN KEY (idRecurso) REFERENCES Recurso(id) ON DELETE CASCADE ON UPDATE CASCADE;
  
ALTER TABLE Recurso
  ADD KEY idAutor(idAutor),
  ADD KEY idTipo(idTipo),
  ADD KEY idCategoria(idCategoria),  
  ADD KEY idProductora(idProductora),
  ADD KEY idEstado(idEstado),
  ADD CONSTRAINT R_1 FOREIGN KEY (idAutor) REFERENCES Autor(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT R_2 FOREIGN KEY (idTipo) REFERENCES TipoRecurso(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT R_3 FOREIGN KEY (idCategoria) REFERENCES Categoria(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT R_4 FOREIGN KEY (idProductora) REFERENCES Productora(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT R_5 FOREIGN KEY (idEstado) REFERENCES EstadoRecurso(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ComentariosSugerencias 
  ADD KEY idPersona(idPersona),
  ADD KEY idRecurso(idRecurso),
  ADD CONSTRAINT CS_1 FOREIGN KEY (idPersona) REFERENCES Persona (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT CS_2 FOREIGN KEY (idRecurso) REFERENCES Recurso(id) ON DELETE CASCADE ON UPDATE CASCADE;
