INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (1,'Simon ','Monk','www.simonmonk.org');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (2,'John ','Bird','www2.ensc.sfu.ca/people/faculty/bird/url/');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (3,'Paul ','Scherz',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (4,'Kimno ','Karvinen',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (5,'José Francisco Piñón Rizo','Piñón Rizo',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (6,'Rafael ','Reina Acedo',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (7,'Jóse Miguel ','Molina Martínez','www.upct.es/iaea/profesores/molina_martinez/');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (8,'Antonio ','Hermosa','www.hermosa.acta.es');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (9,'Eduard ','Ballester ',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (10,'Antonio ','Hermosa Donate','www.hermosa.acta.es');
