INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (4,'Simon ','Monk','www.simonmonk.org');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (5,'John ','Bird','www2.ensc.sfu.ca/people/faculty/bird/url/');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (6,'Paul ','Scherz',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (7,'Kimno ','Karvinen',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (8,'José Francisco Piñón Rizo','Piñón Rizo',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (9,'Rafael ','Reina Acedo',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (10,'Jóse Miguel ','Molina Martínez','www.upct.es/iaea/profesores/molina_martinez/');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (11,'Antonio ','Hermosa','www.hermosa.acta.es');
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (12,'Eduard ','Ballester ',NULL);
INSERT INTO `Autor` (`id`,`nombres`,`apellidos`,`urlWeb`) VALUES (13,'Antonio ','Hermosa Donate','www.hermosa.acta.es');
