INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (2,'Mc Graw Hill ','www.mheducation.com.co');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (3,'Routledge','www.routledge.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (4,'Mc Graw Hill ','www.mheducation.com.co');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (5,'Marker Media','www.makermedia.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (6,'DeLaSalle','www.editorialdelasalle.mx');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (7,'Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (8,'Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (9,'Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (10,'Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (11,'Alfaomega','www.alfaomega.com.mx');
