use Biblioteca;
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Daniel','Florian','http://www.floriandaniel.it/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Roel J.','Wieringa','http://wwwhome.ewi.utwente.nl/~roelw/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Marlon ','Dumas','https://kodu.ut.ee/~dumas/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Yosi','Ben - Asher','http://cs.haifa.ac.il/~yosi/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('James T.','Strieb','http://www.jtstreib.com/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Simon ','Monk','www.simonmonk.org');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('John ','Bird','www2.ensc.sfu.ca/people/faculty/bird/url/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Paul ','Scherz',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Kimno ','Karvinen',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('José Francisco Piñón Rizo','Piñón Rizo',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Rafael ','Reina Acedo',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Jóse Miguel ','Molina Martínez','www.upct.es/iaea/profesores/molina_martinez/');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Antonio ','Hermosa','www.hermosa.acta.es');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Eduard ','Ballester ',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Antonio ','Hermosa Donate','www.hermosa.acta.es');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('John ','Krogstie',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Richard ','Hill',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Mathias  ','Weske',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Jóse Luis ','Gómez Pardo',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Mauro ','Borgo',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Willem-Paul ','De Roever',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Jeremy ','Gibbons','jeremy.gibbons@cs.ox.ac.uk');
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Bir ','Bhanu ',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Zicheng ','Liu',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Davide ','Sangiorgi',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Paúl  ','Wellin',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Michael','Dubois',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Daniel Cohen ','Karen',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Andrew S. ','Tanenbaum',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Ricardo Férnandez ','Del Busto y Ezeta',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Peter ','Lake',NULL);
INSERT INTO `Autor` (`nombres`,`apellidos`,`urlWeb`) VALUES ('Max ','Bramer',NULL);
