use Biblioteca;
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','http://www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','http://www.cambridge.org/');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','https://www.alfaomega.com.co/index.php');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Mc Graw Hill ','www.mheducation.com.co');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Routledge','www.routledge.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Mc Graw Hill ','www.mheducation.com.co');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Marker Media','www.makermedia.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('DeLaSalle','www.editorialdelasalle.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Alfaomega','www.alfaomega.com.mx');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer',' www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Mc Graw Hill Education',NULL);
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('PEARSON','www.pearsoneducacion.net');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Mc Graw Hill Education',NULL);
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
INSERT INTO `Productora` (`nombre`,`urlWeb`) VALUES ('Springer','www.springer.com');
