INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (6,'Springer',' www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (7,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (8,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (9,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (10,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (11,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (12,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (13,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (14,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (15,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (16,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (17,'Cambridge','www.cambridge.org');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (18,'Mc Graw Hill Education',NULL);
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (19,'PEARSON','www.pearsoneducacion.net');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (20,'Mc Graw Hill Education',NULL);
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (21,'Springer','www.springer.com');
INSERT INTO `Productora` (`id`,`nombre`,`urlWeb`) VALUES (22,'Springer','www.springer.com');
